/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jiaki
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ScoringCandidateResumeButton = new javax.swing.JButton();
        QualifiedCandidateListButton = new javax.swing.JButton();
        SchedulingInterviewSlotButton = new javax.swing.JButton();
        ConfirmingInterviewSlotButton = new javax.swing.JButton();
        ApplicationStatusUpdateButton = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Smart Recruitment");

        ScoringCandidateResumeButton.setText("Scoring Candidate Resume");
        ScoringCandidateResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoringCandidateResumeButtonActionPerformed(evt);
            }
        });

        QualifiedCandidateListButton.setText("Qualified Candidate List");
        QualifiedCandidateListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualifiedCandidateListButtonActionPerformed(evt);
            }
        });

        SchedulingInterviewSlotButton.setText("Scheduling Interview Slot");
        SchedulingInterviewSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchedulingInterviewSlotButtonActionPerformed(evt);
            }
        });

        ConfirmingInterviewSlotButton.setText("Confirming Interview Slot");
        ConfirmingInterviewSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmingInterviewSlotButtonActionPerformed(evt);
            }
        });

        ApplicationStatusUpdateButton.setText("Application Status Update");
        ApplicationStatusUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplicationStatusUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SchedulingInterviewSlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QualifiedCandidateListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScoringCandidateResumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmingInterviewSlotButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ApplicationStatusUpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScoringCandidateResumeButton)
                .addGap(18, 18, 18)
                .addComponent(QualifiedCandidateListButton)
                .addGap(18, 18, 18)
                .addComponent(SchedulingInterviewSlotButton)
                .addGap(18, 18, 18)
                .addComponent(ConfirmingInterviewSlotButton)
                .addGap(18, 18, 18)
                .addComponent(ApplicationStatusUpdateButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScoringCandidateResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoringCandidateResumeButtonActionPerformed
        ScoreResumeForm form = new ScoreResumeForm(this); // based on the name of my forms
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ScoringCandidateResumeButtonActionPerformed

    private void ApplicationStatusUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplicationStatusUpdateButtonActionPerformed
        StatusUpdateForm form = new StatusUpdateForm(this); // based on the name of my forms
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ApplicationStatusUpdateButtonActionPerformed

    // Qualified candidate
    private void QualifiedCandidateListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualifiedCandidateListButtonActionPerformed
        QualifiedCandidatesForm form = new QualifiedCandidatesForm(this); // based on the name of my forms
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_QualifiedCandidateListButtonActionPerformed

    private void SchedulingInterviewSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {
        SchedulingInterviewForm form = new SchedulingInterviewForm(this); // based on the name of my forms
        form.setVisible(true);
        this.setVisible(false);
    }                                                             

    private void ConfirmingInterviewSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {
	ConfirmSlotForm form = new ConfirmSlotForm(this); // based on the name of my forms
	form.setVisible(true);
	this.setVisible(false);
    }                                                             





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplicationStatusUpdateButton;
    private javax.swing.JButton ConfirmingInterviewSlotButton;
    private javax.swing.JButton QualifiedCandidateListButton;
    private javax.swing.JButton SchedulingInterviewSlotButton;
    private javax.swing.JButton ScoringCandidateResumeButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
